#!/usr/bin/env bash

# [06] Installer UI Branding
# This script customizes the Debian Installer appearance with custom branding

echo -e "${BLUE}[+] Configuring Debian Installer UI branding..."

# Directory structure for installer customization
INSTALLER_GRAPHICS_DIR="${CONFIG_DIR}/includes.installer/usr/share/graphics"
INSTALLER_THEME_DIR="${CONFIG_DIR}/includes.installer/usr/share/themes/Clearlooks/gtk-2.0"
INSTALLER_NEWT_DIR="${CONFIG_DIR}/includes.installer/usr/lib/newt"

# Create necessary directories
mkdir -p "${INSTALLER_GRAPHICS_DIR}"
mkdir -p "${INSTALLER_THEME_DIR}"
mkdir -p "${INSTALLER_NEWT_DIR}"

# 1. Installer header
echo -e "${BLUE}[+] Installing custom installer header...${NOCOLOR}"

# Check if custom installer logo exists
if [ -f "${INSTALLER_IMG}" ]; then
  cp "${INSTALLER_IMG}" "${INSTALLER_GRAPHICS_DIR}/logo_debian.png"
  echo -e "${GREEN}[✓] Custom installer header copied${NOCOLOR}"
else
  echo -e "${RED}[!] No custom header found, installer will use default Debian header${NOCOLOR}"
fi

# 2. Graphical installer GTK2 theme
echo -e "${BLUE}[+] Generating custom GTK2 theme for graphical installer...${NOCOLOR}"

# Convert hex colors to GTK RGB format (0-65535 range)
hex_to_gtk() {
  local hex=$1
  hex=${hex#\#}
  local r=$(( 16#${hex:0:2} * 257 ))
  local g=$(( 16#${hex:2:2} * 257 ))
  local b=$(( 16#${hex:4:2} * 257 ))
  echo "$r $g $b"
}

PRIMARY_RGB=$(hex_to_gtk "$INSTALLER_PRIMARY_COLOR")
SECONDARY_RGB=$(hex_to_gtk "$INSTALLER_SECONDARY_COLOR")
TEXT_RGB=$(hex_to_gtk "$INSTALLER_TEXT_COLOR")
BG_RGB=$(hex_to_gtk "$INSTALLER_BG_COLOR")

# Generate custom gtkrc with branding colors
cat > "${INSTALLER_THEME_DIR}/gtkrc" <<EOF
# Custom GTK2 Theme for Debian Installer
# Generated by DisplayOS Build System
# Colors based on: $INSTALLER_PRIMARY_COLOR (primary), $INSTALLER_SECONDARY_COLOR (secondary)

style "default" {
  fg[NORMAL]      = { $TEXT_RGB }
  fg[PRELIGHT]    = { $TEXT_RGB }
  fg[ACTIVE]      = { $TEXT_RGB }
  fg[SELECTED]    = { $TEXT_RGB }
  fg[INSENSITIVE] = { 30000 30000 30000 }

  bg[NORMAL]      = { $BG_RGB }
  bg[PRELIGHT]    = { $PRIMARY_RGB }
  bg[ACTIVE]      = { $SECONDARY_RGB }
  bg[SELECTED]    = { $PRIMARY_RGB }
  bg[INSENSITIVE] = { 50000 50000 50000 }

  base[NORMAL]    = { 65535 65535 65535 }
  base[PRELIGHT]  = { $PRIMARY_RGB }
  base[ACTIVE]    = { $SECONDARY_RGB }
  base[SELECTED]  = { $PRIMARY_RGB }

  text[NORMAL]    = { 0 0 0 }
  text[PRELIGHT]  = { $TEXT_RGB }
  text[ACTIVE]    = { $TEXT_RGB }
  text[SELECTED]  = { $TEXT_RGB }
}

# Banner (top logo area) styling
style "banner" {
  bg[NORMAL] = { $PRIMARY_RGB }
  fg[NORMAL] = { $TEXT_RGB }
}

# Progress bar styling
style "progressbar" {
  bg[PRELIGHT] = { $PRIMARY_RGB }
  fg[PRELIGHT] = { $TEXT_RGB }
  bg[SELECTED] = { $SECONDARY_RGB }
}

# Button styling
style "button" {
  bg[NORMAL]   = { $BG_RGB }
  bg[PRELIGHT] = { $PRIMARY_RGB }
  bg[ACTIVE]   = { $SECONDARY_RGB }
  fg[NORMAL]   = { 0 0 0 }
  fg[PRELIGHT] = { $TEXT_RGB }
  fg[ACTIVE]   = { $TEXT_RGB }
}

# Menu styling
style "menu" {
  bg[NORMAL]   = { $BG_RGB }
  bg[PRELIGHT] = { $PRIMARY_RGB }
  fg[NORMAL]   = { 0 0 0 }
  fg[PRELIGHT] = { $TEXT_RGB }
}

# Apply styles
class "GtkWidget" style "default"
class "GtkButton" style "button"
class "GtkProgressBar" style "progressbar"
class "GtkMenu*" style "menu"
widget "*banner*" style "banner"
widget "*Banner*" style "banner"
EOF

echo -e "${GREEN}[✓] GTK2 theme generated with colors: $INSTALLER_PRIMARY_COLOR${NOCOLOR}"

# 3. TEXT-MODE INSTALLER COLORS (NEWT)
echo -e "${BLUE}[+] Generating custom palette for text-mode installer...${NOCOLOR}"

# Generate newt palette file
# Format: element=foreground,background
# Available colors: black, blue, green, cyan, red, magenta, yellow, white,
#                   brightblue, brightgreen, brightcyan, brightred, brightmagenta, brightyellow
cat > "${INSTALLER_NEWT_DIR}/palette" <<'EOF'
# Custom Newt Palette for Debian Installer Text Mode
# Generated by DisplayOS Build System

# Main window colors
root=white,blue
border=white,blue
window=white,blue
shadow=black,black
title=yellow,blue

# Dialog elements
button=black,cyan
actbutton=white,blue
compactbutton=white,blue

# Text entry fields
entry=black,lightgray
disentry=gray,lightgray

# Selection list
listbox=black,lightgray
actlistbox=black,cyan
sellistbox=white,blue
actsellistbox=white,blue

# Checkboxes and radio buttons
checkbox=black,lightgray
actcheckbox=white,blue

# Text display
textbox=black,lightgray
acttextbox=white,blue

# Progress bar
emptyscale=white,blue
fullscale=white,cyan

# Help line
helpline=white,blue

# Root text (main background)
roottext=white,blue
EOF

echo -e "${GREEN}[✓] Text-mode palette generated${NOCOLOR}"
echo -e "${GREEN}[✓] Debian Installer UI branding complete${NOCOLOR}"
