#!/bin/bash
# =============================================================================
# DisplayOS Kiosk Setup Script
# =============================================================================
#
# This script configures the kiosk environment on an installed system
#
# Usage:
#   sudo ./setup_kiosk.sh [options]
#
# Options:
#   --browser=BROWSER   Set browser (chromium or firefox)
#   --url=URL           Set target URL
#   --no-watchdog       Disable watchdog service
#   --help              Show help
#
# =============================================================================

set -euo pipefail

# =============================================================================
# CONFIGURATION
# =============================================================================

readonly SCRIPT_NAME="DisplayOS Kiosk Setup"
readonly CONFIG_DIR="/etc/displayos"
readonly CONFIG_FILE="$CONFIG_DIR/config.conf"
readonly LOG_DIR="/var/log/displayos"
readonly DISPLAYOS_USER="displayos"

# Colors
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[0;33m'
readonly RED='\033[0;31m'
readonly NC='\033[0m'

# =============================================================================
# FUNCTIONS
# =============================================================================

log_info() {
    echo -e "${GREEN}[INFO]${NC} $*"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*" >&2
}

show_help() {
    cat << EOF
$SCRIPT_NAME

Configure the DisplayOS kiosk environment.

Usage:
    sudo $0 [options]

Options:
    --browser=BROWSER   Set browser (chromium or firefox)
    --url=URL           Set target URL
    --no-watchdog       Disable watchdog service
    --help              Show this help

Examples:
    sudo $0 --url=https://dashboard.example.com
    sudo $0 --browser=firefox --url=https://example.com
EOF
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root"
        exit 1
    fi
}

create_directories() {
    log_info "Creating directories..."
    
    mkdir -p "$CONFIG_DIR"
    mkdir -p "$LOG_DIR"
    mkdir -p "/home/$DISPLAYOS_USER/.config/openbox"
    mkdir -p "/home/$DISPLAYOS_USER/.config/chromium"
    mkdir -p "/home/$DISPLAYOS_USER/.mozilla/firefox"
    
    # Set permissions
    chmod 755 "$CONFIG_DIR"
    chmod 755 "$LOG_DIR"
    chown -R "$DISPLAYOS_USER:$DISPLAYOS_USER" "/home/$DISPLAYOS_USER/.config"
    chown -R "$DISPLAYOS_USER:$DISPLAYOS_USER" "/home/$DISPLAYOS_USER/.mozilla"
}

create_user() {
    log_info "Creating displayos user..."
    
    if ! id "$DISPLAYOS_USER" &>/dev/null; then
        useradd -m -s /bin/bash -G sudo,audio,video,netdev "$DISPLAYOS_USER"
        echo "$DISPLAYOS_USER:displayos" | chpasswd
        log_info "User '$DISPLAYOS_USER' created (default password: displayos)"
    else
        log_info "User '$DISPLAYOS_USER' already exists"
    fi
}

setup_config() {
    local browser="${1:-chromium}"
    local url="${2:-https://example.com}"
    
    log_info "Setting up configuration..."
    
    if [[ -f "$CONFIG_FILE" ]]; then
        log_info "Configuration file exists, updating..."
        
        # Update existing values
        sed -i "s|^TARGET_URL=.*|TARGET_URL=$url|" "$CONFIG_FILE"
        sed -i "s|^BROWSER=.*|BROWSER=$browser|" "$CONFIG_FILE"
    else
        # Create new configuration
        cat > "$CONFIG_FILE" << EOF
# DisplayOS Configuration
# Generated by setup_kiosk.sh on $(date)

TARGET_URL=$url
BROWSER=$browser
DISPLAY_MODE=fullscreen
WIFI_SSID=
WIFI_PASSWORD=
WATCHDOG_TIMEOUT=30
WATCHDOG_ENABLED=true
HOSTNAME=displayos
TIMEZONE=UTC
KEYBOARD_LAYOUT=no
VIRTUAL_KEYBOARD=false
SHOW_CURSOR=true
CURSOR_HIDE_TIMEOUT=5
SSH_ENABLED=false
AUTO_UPDATES=true
DEBUG_MODE=false
LOG_FILE=/var/log/displayos/kiosk.log
EOF
    fi
    
    # Secure the configuration file
    chmod 600 "$CONFIG_FILE"
    chown root:root "$CONFIG_FILE"
    
    log_info "Configuration saved to $CONFIG_FILE"
}

setup_browser_profile() {
    local browser="$1"
    
    log_info "Setting up $browser profile..."
    
    if [[ "$browser" == "chromium" ]]; then
        # Chromium first run configuration
        local chromium_prefs="/home/$DISPLAYOS_USER/.config/chromium/Default/Preferences"
        mkdir -p "$(dirname "$chromium_prefs")"
        
        cat > "$chromium_prefs" << 'EOF'
{
    "browser": {
        "check_default_browser": false,
        "show_home_button": false
    },
    "session": {
        "restore_on_startup": 4,
        "startup_urls": []
    },
    "profile": {
        "default_content_setting_values": {
            "notifications": 2
        }
    }
}
EOF
        chown "$DISPLAYOS_USER:$DISPLAYOS_USER" "$chromium_prefs"
        
    elif [[ "$browser" == "firefox" ]]; then
        # Firefox profile
        local ff_profile="/home/$DISPLAYOS_USER/.mozilla/firefox/kiosk.default"
        mkdir -p "$ff_profile"
        
        cat > "$ff_profile/user.js" << 'EOF'
// DisplayOS Firefox Kiosk Profile
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.firstrunSkipsHomepage", true);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
EOF
        chown -R "$DISPLAYOS_USER:$DISPLAYOS_USER" "/home/$DISPLAYOS_USER/.mozilla"
    fi
}

setup_openbox() {
    log_info "Configuring Openbox window manager..."
    
    local openbox_dir="/home/$DISPLAYOS_USER/.config/openbox"
    
    # Autostart
    cat > "$openbox_dir/autostart" << 'EOF'
# DisplayOS Openbox Autostart

# Disable screen saver and power management
xset s off &
xset -dpms &
xset s noblank &

# Start network manager applet
nm-applet &

# Hide cursor after timeout
if command -v unclutter &>/dev/null; then
    unclutter -idle 5 -root &
fi

# Virtual keyboard (if enabled)
if grep -q "VIRTUAL_KEYBOARD=true" /etc/displayos/config.conf 2>/dev/null; then
    onboard --size=800x200 &
fi
EOF
    
    # RC configuration with keyboard shortcuts
    cat > "$openbox_dir/rc.xml" << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<openbox_config xmlns="http://openbox.org/3.4/rc">
  
  <resistance>
    <strength>10</strength>
    <screen_edge_strength>20</screen_edge_strength>
  </resistance>
  
  <focus>
    <focusNew>yes</focusNew>
    <followMouse>no</followMouse>
  </focus>
  
  <placement>
    <policy>Smart</policy>
    <center>yes</center>
  </placement>
  
  <desktops>
    <number>1</number>
  </desktops>
  
  <keyboard>
    <!-- F5: Reload browser page -->
    <keybind key="F5">
      <action name="Execute">
        <command>xdotool key --clearmodifiers F5</command>
      </action>
    </keybind>
    
    <!-- Ctrl+Alt+Delete: Exit kiosk mode -->
    <keybind key="C-A-Delete">
      <action name="Execute">
        <command>/usr/local/bin/displayos-exit-kiosk</command>
      </action>
    </keybind>
    
    <!-- Ctrl+Alt+K: Toggle virtual keyboard -->
    <keybind key="C-A-k">
      <action name="Execute">
        <command>dbus-send --type=method_call --dest=org.onboard.Onboard /org/onboard/Onboard/Keyboard org.onboard.Onboard.Keyboard.ToggleVisible 2>/dev/null || onboard &</command>
      </action>
    </keybind>
    
    <!-- Ctrl+Alt+W: Open Network Manager GUI -->
    <keybind key="C-A-w">
      <action name="Execute">
        <command>nm-connection-editor</command>
      </action>
    </keybind>
    
    <!-- Ctrl+Alt+T: Open terminal (for debugging) -->
    <keybind key="C-A-t">
      <action name="Execute">
        <command>xterm</command>
      </action>
    </keybind>
  </keyboard>
  
  <applications>
    <!-- Chromium kiosk mode -->
    <application class="Chromium*">
      <fullscreen>yes</fullscreen>
      <decor>no</decor>
      <focus>yes</focus>
      <layer>normal</layer>
    </application>
    
    <!-- Firefox kiosk mode -->
    <application class="Firefox*">
      <fullscreen>yes</fullscreen>
      <decor>no</decor>
      <focus>yes</focus>
      <layer>normal</layer>
    </application>
    
    <!-- Network manager on top -->
    <application class="Nm-connection-editor">
      <fullscreen>no</fullscreen>
      <decor>yes</decor>
      <focus>yes</focus>
      <layer>above</layer>
    </application>
    
    <!-- Virtual keyboard -->
    <application class="Onboard">
      <fullscreen>no</fullscreen>
      <decor>no</decor>
      <skip_taskbar>yes</skip_taskbar>
      <layer>above</layer>
    </application>
  </applications>
  
</openbox_config>
EOF
    
    chown -R "$DISPLAYOS_USER:$DISPLAYOS_USER" "$openbox_dir"
    log_info "Openbox configuration complete"
}

setup_systemd_services() {
    local enable_watchdog="$1"
    
    log_info "Setting up systemd services..."
    
    # Ensure services are installed
    if [[ ! -f /etc/systemd/system/displayos-kiosk.service ]]; then
        log_warn "Kiosk service not found, services may need to be installed"
    fi
    
    # Enable/disable services
    systemctl daemon-reload
    
    if systemctl list-unit-files | grep -q displayos-kiosk; then
        systemctl enable displayos-kiosk.service
        log_info "Enabled displayos-kiosk.service"
    fi
    
    if [[ "$enable_watchdog" == "true" ]]; then
        if systemctl list-unit-files | grep -q displayos-watchdog; then
            systemctl enable displayos-watchdog.service
            log_info "Enabled displayos-watchdog.service"
        fi
    else
        if systemctl list-unit-files | grep -q displayos-watchdog; then
            systemctl disable displayos-watchdog.service || true
            log_info "Disabled displayos-watchdog.service"
        fi
    fi
}

setup_autologin() {
    log_info "Configuring autologin..."
    
    # LightDM configuration
    mkdir -p /etc/lightdm/lightdm.conf.d
    cat > /etc/lightdm/lightdm.conf.d/50-displayos-autologin.conf << EOF
[Seat:*]
autologin-user=$DISPLAYOS_USER
autologin-user-timeout=0
user-session=openbox
autologin-session=openbox
EOF
    
    log_info "Autologin configured for user: $DISPLAYOS_USER"
}

# =============================================================================
# MAIN
# =============================================================================

main() {
    local browser="chromium"
    local url=""
    local enable_watchdog="true"
    
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --browser=*)
                browser="${1#*=}"
                ;;
            --url=*)
                url="${1#*=}"
                ;;
            --no-watchdog)
                enable_watchdog="false"
                ;;
            --help)
                show_help
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                show_help
                exit 1
                ;;
        esac
        shift
    done
    
    # Validate browser
    if [[ "$browser" != "chromium" ]] && [[ "$browser" != "firefox" ]]; then
        log_error "Invalid browser: $browser (must be chromium or firefox)"
        exit 1
    fi
    
    check_root
    
    echo -e "\n${GREEN}========================================${NC}"
    echo -e "${GREEN}  $SCRIPT_NAME${NC}"
    echo -e "${GREEN}========================================${NC}\n"
    
    create_user
    create_directories
    setup_config "$browser" "$url"
    setup_browser_profile "$browser"
    setup_openbox
    setup_autologin
    setup_systemd_services "$enable_watchdog"
    
    echo -e "\n${GREEN}Kiosk setup complete!${NC}"
    echo -e "Configuration: ${CONFIG_FILE}"
    echo -e "Default URL: ${url:-https://example.com}"
    echo -e "Browser: ${browser}"
    echo -e "\nReboot to start kiosk mode, or run:"
    echo -e "  sudo systemctl start displayos-kiosk"
}

main "$@"
